### ISSUE TITLE
Image uploads fail after first successful upload..

### ISSUE THREAD

**Issue by NeTgHoStKiLlEr** [DaleGia/ESPCaptiveImagePortal#1]
It allowed me to upload a gif and a jpg the first time I tried it, but no longer. Now, It'll upload the first image fine, and then always fail when trying to upload any more. Not sure why.

**Comment by DaleGia** [comment]
Hi, sounds as if your image files are too big for the SPIFFS memory. Id recomend making your images no.larger than 100kBs to ensure their fast upload/download and to make sure multiple images can be loaded onto SPIFFS.

**Comment by NeTgHoStKiLlEr** [comment]
I actually made sure they were all under 360 pixels wide and also 30-40kb each.. the two files that do work, only work on the first upload. Using IDE 1.8.13

**Comment by DaleGia** [comment]
Hmm that is interesting. I would try reformatting the SPIFFS and giving it another go and seeing if that works. Otherwise I am not sure how much help I can give without more debug information. You may have stumbled across an unidentified bug, but it seems like it may be hard to replicate.
